import jsPDF from "jspdf";

export function downloadReport(
  previousPolicy: string,
  updatedPolicy: string,
  totalChanges: number,
  addedPolicies: number,
  removedPolicies: number,
  aiSummary: string
) {
  const doc = new jsPDF();

  let y = 20;

  // ==========================
  // Header
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(0, 70, 140);
  doc.text("Policy Matrix", 105, y, { align: "center" });

  y += 10;

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.text(
    "AI-Powered Healthcare Policy Analysis Report",
    105,
    y,
    { align: "center" }
  );

  y += 15;

  doc.setDrawColor(0, 70, 140);
  doc.line(20, y, 190, y);

  y += 10;

  // ==========================
  // Report Information
  // ==========================

  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Report Information", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(
    `Generated On: ${new Date().toLocaleString()}`,
    20,
    y
  );

  y += 8;

  doc.text("Application: Policy Matrix", 20, y);

  y += 15;

  // ==========================
  // Policy Information
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Policy Information", 20, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(`Previous Policy: ${previousPolicy}`, 20, y);

  y += 8;

  doc.text(`Updated Policy: ${updatedPolicy}`, 20, y);

  y += 15;

  // ==========================
  // Analysis Summary
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Analysis Summary", 20, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(`Total Changes : ${totalChanges}`, 25, y);

  y += 8;

  doc.text(`Added Policies : ${addedPolicies}`, 25, y);

  y += 8;

  doc.text(`Removed Policies : ${removedPolicies}`, 25, y);

  y += 15;

  // ==========================
  // AI Summary
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("AI Policy Insights", 20, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const lines = doc.splitTextToSize(aiSummary, 170);

  doc.text(lines, 20, y);

  y += lines.length * 6 + 10;

  // ==========================
  // Footer
  // ==========================

  doc.setDrawColor(180);
  doc.line(20, 280, 190, 280);

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by Policy Matrix | AI-Powered Healthcare Policy Comparison",
    105,
    287,
    { align: "center" }
  );

  doc.save("Policy_Matrix_Report.pdf");
}